#!/usr/bin/env bash
#
# thin_agent 配置同步到设备
# - 把 ~/.thin_agent 的私有配置复制到设备目录
# - 默认仅同步 demo.model.yaml + 过滤后的 deepseek.env（不含云 API Key / 飞书凭据）
#
# 用法:
#   bash config.sh
#   bash config.sh --cloud-llm
#   bash config.sh --with-feishu
#   bash config.sh --cloud-llm --with-feishu
#   LOCAL_AGENT_DIR=/root/.thin_agent DEVICE_ROOT=/data/thin_agent bash config.sh
set -euo pipefail

LOCAL_AGENT_DIR="${LOCAL_AGENT_DIR:-/root/.thin_agent}"
DEVICE_ROOT="${DEVICE_ROOT:-/data/thin_agent}"
WITH_CLOUD_LLM=0
WITH_FEISHU=0
ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
# adb: Linux adb 优先；WSL 下回退 Windows adb.exe（见 scripts/resolve_adb.sh）
ADB="$(bash "$ROOT_DIR/scripts/resolve_adb.sh")"

usage() {
  cat <<'EOF'
Usage:
  bash config.sh [options]

Options:
  --cloud-llm     同步 DEEPSEEK_API_KEY/GLM_API_KEY（默认不同步，避免把云 Key 推到设备）
  --with-feishu   同步 FEISHU_APP_ID / FEISHU_APP_SECRET（设备跑 IM 网关时需要）
  -h, --help      Show this help

Always synced:
  config/demo.model.yaml
  deepseek.env 中的 THIN_AGENT_* 变量

Examples:
  bash config.sh                              # 仅 profile + THIN_AGENT_*
  bash config.sh --cloud-llm                  # 额外推云 LLM API Key
  bash config.sh --with-feishu                # 额外推飞书凭据（本地网关）
  bash config.sh --cloud-llm --with-feishu    # 云 + 飞书全开
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --cloud-llm) WITH_CLOUD_LLM=1; shift ;;
    --with-feishu) WITH_FEISHU=1; shift ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown arg: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

[[ -f "$LOCAL_AGENT_DIR/demo.model.yaml" ]] || { echo "missing $LOCAL_AGENT_DIR/demo.model.yaml" >&2; exit 2; }
ENV_SRC="$LOCAL_AGENT_DIR/deepseek.env"
[[ -f "$ENV_SRC" ]] || ENV_SRC="$LOCAL_AGENT_DIR/zai.env"
[[ -f "$ENV_SRC" ]] || { echo "missing $LOCAL_AGENT_DIR/deepseek.env" >&2; exit 2; }

extract_env_line() {
  local key="$1"
  local line
  line="$(grep -E "^${key}=" "$ENV_SRC" | head -1 || true)"
  [[ -n "$line" ]] && printf '%s\n' "$line"
}

TMP_ENV="$(mktemp)"
trap 'rm -f "$TMP_ENV"' EXIT

{
  echo "# thin_agent device env (generated by config.sh, do not commit)"
  rg '^(THIN_AGENT_[A-Z0-9_]+)=' "$ENV_SRC" 2>/dev/null || true
  if [[ "$WITH_CLOUD_LLM" == "1" ]]; then
    extract_env_line DEEPSEEK_API_KEY || true
    extract_env_line GLM_API_KEY || true
  fi
  if [[ "$WITH_FEISHU" == "1" ]]; then
    extract_env_line FEISHU_APP_ID || true
    extract_env_line FEISHU_APP_SECRET || true
  fi
} > "$TMP_ENV"

"$ADB" wait-for-device
"$ADB" root || true
sleep 1
"$ADB" wait-for-device
"$ADB" shell "mkdir -p '$DEVICE_ROOT/config'"

"$ADB" push "$LOCAL_AGENT_DIR/demo.model.yaml" "/tmp/demo.model.yaml" >/dev/null
"$ADB" shell "mv /tmp/demo.model.yaml '$DEVICE_ROOT/config/demo.model.yaml' && chmod 600 '$DEVICE_ROOT/config/demo.model.yaml'"

"$ADB" push "$TMP_ENV" "/tmp/deepseek.env" >/dev/null
"$ADB" shell "mv /tmp/deepseek.env '$DEVICE_ROOT/deepseek.env' && chmod 600 '$DEVICE_ROOT/deepseek.env'"

"$ADB" shell sync

ENV_PARTS="THIN_AGENT_*"
[[ "$WITH_CLOUD_LLM" == "1" ]] && ENV_PARTS+=" DEEPSEEK_API_KEY GLM_API_KEY"
[[ "$WITH_FEISHU" == "1" ]] && ENV_PARTS+=" FEISHU_APP_ID FEISHU_APP_SECRET"

echo ">> config synced to $DEVICE_ROOT"
echo "   updated: config/demo.model.yaml"
echo "   deepseek.env includes: $ENV_PARTS"
